#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

alias \
		slp="systemctl suspend" \
		slpl="systemctl suspend && customi3lock" \
		slple="systemctl suspend && customi3lock && exit" \
		slpe="systemctl suspend && exit" \
		p="sudo pacman" \
		virt="virt-manager && exit" \
		news="newsboat" \
		v="nvim" \

# Git commands
alias \
		gskip="git update-index --skip-worktree" \
		gnoskip="git update-index --no-skip-worktree" \
		gcheck="git ls-files -v|grep '^S'" \
