#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

alias \
		slp="systemctl suspend" \
		slpl="systemctl suspend && customi3lock" \
		slple="systemctl suspend && customi3lock && exit" \
		slpe="systemctl suspend && exit" \
		p="sudo pacman" \
		virt="virt-manager && exit" \
		news="newsboat" \
		v="nvim" \

# Git commands
# Skip worktree related commands
alias \
		gskip="git update-index --skip-worktree" \
		gnoskip="git update-index --no-skip-worktree" \
		gcheck="git ls-files -v|grep '^S'" \

# Committing
alias \
		ga="git add" \
		gc="git commit" \
		gca="git commit -a" \
		gs="git status" \
		gd="git diff" \
		gp="git push" \
