#! /bin/sh

# Set Variables
mainmonitor=HDMI-0
secondarymonitor=HDMI3
DESKTOPINTEGRATION=false

sxhkd &
xset -dpms s off
pgrep -x spotify > /dev/null || spotify &
pgrep -x chromium > /dev/null || chromium &
pgrep -x discord > /dev/null || discord &
pgrep -x whatsdesk > /dev/null || whatsdesk &
pgrep -x mailspring > /dev/null || mailspring &
pgrep -x /usr/lib/geoclue-2.0/demos/agent> /dev/null || /usr/lib/geoclue-2.0/demos/agent &
pgrep -x redshift-gtk> /dev/null || redshift-gtk &
pgrep -x picom > /dev/null || picom &
pgrep -x todoist > /dev/null || todoist &
pgrep -x /opt/urserver/urserver > /dev/null || /opt/urserver/urserver --daemon &
pgrep bspswallow || bspswallow &
#kdeconnect-cli --pair --device 1db7c78dd7125b39

#polybar bspwm &
$HOME/.config/polybar/launch.sh

bspc monitor $mainmonitor -d I III V VII IX
bspc monitor $secondarymonitor -d II IV VI VIII X

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# Use wmctrl to set them to the right window
wmctrl -r todoist -t 0
while IFS= read -r line; do
    wmctrl -ir $line -t 5
done <<< $(wmctrl -l | awk '/Firefox/{print $1}')

while IFS= read -r line; do
    wmctrl -ir $line -t 5
done <<< $(wmctrl -l | awk '/Chromium/{print $1}')
wmctrl -r discord -t 7
wmctrl -r whatsdesk -t 7
wmctrl -r mailspring -t 8
wmctrl -r Spotify -t 9

# Set bspc rules
bspc rule -a Emacs state=tiled
bspc rule -a BloonsTD6 state=tiled
bspc rule -a steam_app_528230 state=tiled
bspc rule -a Android* state=float
bspc rule -a discord desktop='^8'
bspc rule -a whatsdesk desktop='^8'
bspc rule -a mailspring desktop='^9'
bspc rule -a spotify desktop='^10'
bspc config external_rules_command ./android

xrandr --output $mainmonitor --auto --pos 0x0 --output $secondarymonitor --auto --pos 2560x360
feh --bg-scale /home/tobins/Pictures/Backgrounds/anime-city-lights-night-rain-umbrella-sky-5k-ou-2560x1440.jpg --bg-fill /home/tobins/Pictures/Backgrounds/1920x1080/8fa9975a9e6f6251ee55a4a26f06d440.jpg
#feh --bg-scale /home/tobins/Pictures/Backgrounds/1920x1080/8fa9975a9e6f6251ee55a4a26f06d440.jpg --bg-fill /home/tobins/Pictures/Backgrounds/anime-city-lights-night-rain-umbrella-sky-5k-ou-2560x1440.jpg
