#! /bin/sh

# Set Variables
mainmonitor=DP-4
secondarymonitor=HDMI-0
DESKTOPINTEGRATION=false

sxhkd &
xset s 1200 1200
pgrep -x spotify > /dev/null || spotify &
pgrep -x firefox > /dev/null || firefox &
pgrep -x discord > /dev/null || discord &
pgrep -x whatsdesk > /dev/null || whatsdesk &
pgrep -x thunderbird > /dev/null || thunderbird &
pgrep -x /usr/lib/geoclue-2.0/demos/agent> /dev/null || /usr/lib/geoclue-2.0/demos/agent &
pgrep -x redshift-gtk> /dev/null || redshift-gtk &
pgrep -x picom > /dev/null || picom &
pgrep -x todoist > /dev/null || todoist &
pgrep -x cadmus > /dev/null || cadmus &
pgrep -x polkit-dumb-agent > /dev/null || pulkit-dumb-agent &
pgrep -x barrier > /dev/null || barrier &
pgrep bspswallow || bspswallow &
#kdeconnect-cli --pair --device 1db7c78dd7125b39
kdeconnect-cli --refresh

#polybar bspwm &
$HOME/.config/polybar/launch.sh

bspc monitor $mainmonitor -d I III V VII IX
bspc monitor $secondarymonitor -d II IV VI VIII X

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# Use wmctrl to set them to the right window
wmctrl -r todoist -t 0
while IFS= read -r line; do
    wmctrl -ir $line -t 5
done <<< $(wmctrl -l | awk '/Firefox/{print $1}')

while IFS= read -r line; do
    wmctrl -ir $line -t 5
done <<< $(wmctrl -l | awk '/Chromium/{print $1}')
wmctrl -r todoist -t 6
wmctrl -r discord -t 7
wmctrl -r whatsdesk -t 7
wmctrl -r thunderbird -t 8
wmctrl -r Spotify -t 9

# Set bspc rules
bspc rule -a Emacs state=tiled
bspc rule -a BloonsTD6 state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a steam_app_528230 state=tiled
bspc rule -a Android* state=float
bspc rule -a Vampire_Survivors state=floating rectangle=1200+800+0+0
bspc rule -a "steam_app_3480" state=floating rectangle=1200+1200+0+0

bspc rule -a discord desktop='^8'
bspc rule -a whatsdesk desktop='^8'
bspc rule -a thunderbird desktop='^9'
bspc rule -a spotify desktop='^10'


bspc config external_rules_command ./android

#xrandr --output $mainmonitor --auto --pos 0x0 --output $secondarymonitor --auto --pos 2560x360
feh --bg-scale /home/tobins/Pictures/Backgrounds/2560x1440/cyber-city-anime-artwork.jpg --bg-fill /home/tobins/Pictures/Backgrounds/1920x1080/Anime-Retro-Desktop-Wallpaper-106387.jpg
#feh --bg-scale /home/tobins/Pictures/Backgrounds/1920x1080/Anime-Retro-Desktop-Wallpaper-106387.jpg --bg-fill /home/tobins/Pictures/Backgrounds/2560x1440/cyber-city-anime-artwork.jpg 
